### GET all blogs
GET http://localhost:3001/api/blogs

### POST create new blogs
POST http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kb2UiLCJpZCI6IjY3ZDNhY2JmYTQyY2JhNTZmZjUwNmEwMSIsImlhdCI6MTc0MTkyNTcyMn0.2QNZhU8n-yierlIH58q1pA3OUvdbf5Eg09f0EJ6wJyU
Content-Type: application/json

{
  "author": "John Doe",
  "title": "Hello, World",
  "url": "https://example.com",
  "likes": 0
}
