### GET all users
GET http://localhost:3001/api/users

### POST create new users
POST http://localhost:3001/api/users
content-type: application/json

{
    "username": "johndoe2",
    "name": "John Doe No.2",
    "password": "password"
}